apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.controller.name}}
  labels:
    app: {{ .Release.Name }}-{{ .Values.controller.name}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.controller.name}}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.controller.name}}
        release: {{ .Release.Name }}
        {{- if .Values.controller.podLabels }}
        {{ toYaml .Values.controller.podLabels | nindent 8}}
        {{- end }}
      {{- if .Values.controller.podAnnotations }}
      annotations:
{{ toYaml .Values.controller.podAnnotations | indent 8}}{{- end }}
    spec:
      serviceAccountName: {{ .Values.controller.serviceAccount | quote }}
      {{- if .Values.controller.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          image: "{{ .Values.images.controller }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          command: [ "workflow-controller" ]
          args:
          - "--configmap"
          - "{{ .Release.Name }}-{{ .Values.controller.name}}-configmap"
          - "--executor-image"
          - "{{ .Values.images.executor }}"
          - "--loglevel"
          - "{{ .Values.controller.logging.level }}"
          - "--gloglevel"
          - "{{ .Values.controller.logging.globallevel }}"
          {{- if .Values.singleNamespace }}
          - "--namespaced"
          {{- end }}
          {{- with .Values.controller.workflowWorkers }}
          - "--workflow-workers"
          - {{ . | quote }}
          {{- end }}
          {{- with .Values.controller.podWorkers }}
          - "--pod-workers"
          - {{ . | quote }}
          {{- end }}
          {{- if .Values.controller.extraArgs }}
          {{- toYaml .Values.controller.extraArgs | nindent 10 }}
          {{- end }}
          env:
          - name: ARGO_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: LEADER_ELECTION_IDENTITY
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          {{- with .Values.controller.extraEnv }}
            {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.controller.resources }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          {{- end }}  
          ports:
            - name: health
              containerPort: 6060
              protocol: TCP
          {{- if .Values.controller.metricsConfig.enabled }}
            - name: metrics
              containerPort: 8080
              protocol: TCP
          {{- end }}
      {{- with .Values.images.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.controller.priorityClassName }}
      priorityClassName: {{ .Values.controller.priorityClassName }}
      {{- end }}
